import AppUI
import ComposableArchitecture
import SwiftUI

/// The simulator beside the terminal: a device menu, its controls, and its live screen.
public struct SimulatorPaneView: View {
	let store: StoreOf<SimulatorPaneReducer>
	/// The space the panel offers, from which the pane takes a width that fits the device's
	/// screen at the available height.
	let availableSize: CGSize
	/// The repository whose terminal the pane is beside, which its close button hides it for.
	let repositoryPath: String
	/// The workspace or project the Run button builds; `nil` when the repository has none.
	let projectPath: String?
	/// Whether the repository has a tab that Run opened, which Stop interrupts.
	let hasRunTab: Bool
	/// Interrupts what runs in the run tab (Ctrl-C). The terminal's panes are not in any store,
	/// so the panel does this, not the reducer.
	let onStop: () -> Void

	public init(
		store: StoreOf<SimulatorPaneReducer>,
		availableSize: CGSize,
		repositoryPath: String,
		projectPath: String?,
		hasRunTab: Bool,
		onStop: @escaping () -> Void
	) {
		self.store = store
		self.availableSize = availableSize
		self.repositoryPath = repositoryPath
		self.projectPath = projectPath
		self.hasRunTab = hasRunTab
		self.onStop = onStop
	}

	private static let headerHeight: CGFloat = 36
	private static let runBarHeight: CGFloat = 40
	private static let screenPadding: CGFloat = 12

	/// Wide enough for the device's screen at the height left under the header, within limits that
	/// keep the terminal usable.
	private var paneWidth: CGFloat {
		let aspect: CGFloat = if let size = store.selectedDevice?.displayedPixelSize, size.height > 0 {
			size.width / size.height
		}
		else {
			0.46
		}
		let screenHeight = max(availableSize.height - Self.headerHeight - Self.runBarHeight - Self.screenPadding * 2, 100)
		let fitting = screenHeight * aspect + Self.screenPadding * 2
		return min(max(fitting, 280), max(availableSize.width * 0.5, 280))
	}

	public var body: some View {
		VStack(spacing: 0) {
			header
			Divider()
			if !store.isClaudeCodeConnected {
				connectBanner
				Divider()
			}
			if let message = store.errorMessage ?? store.loadErrorMessage {
				errorBanner(message)
				Divider()
			}
			content
				// Over the screen rather than above it, so saving does not shrink the device.
				.overlay(alignment: .top) {
					if let notice = store.notice {
						noticeBanner(notice)
							.transition(.move(edge: .top).combined(with: .opacity))
					}
				}
				.animation(.easeOut(duration: 0.2), value: store.notice)
			Divider()
			runBar
		}
		.frame(width: paneWidth)
		.background(Color(NSColor.underPageBackgroundColor))
		// Restarted with the repository, so switching between two repositories that both show the
		// pane switches to the other's device.
		.task(id: repositoryPath) {
			await store.send(.task(repositoryPath: repositoryPath)).finish()
		}
		// Also when the project appears — generated by Tuist while the pane is open.
		.task(id: projectPath) {
			store.send(.projectChanged(projectPath))
		}
	}

	// MARK: - Run

	/// Below the screen: which scheme to build, and Run / Stop for the device shown above.
	private var runBar: some View {
		HStack(spacing: 8) {
			if projectPath == nil {
				Text("No Xcode project to run")
					.scaledFont(.caption)
					.foregroundStyle(.secondary)
					.lineLimit(1)
			}
			else if store.hasLoadedSchemes, store.schemes.isEmpty {
				Text("No scheme here launches an app")
					.scaledFont(.caption)
					.foregroundStyle(.secondary)
					.lineLimit(1)
					.help("Only shared schemes and your own, saved as .xcscheme files, are listed.")
			}
			else {
				schemeMenu
			}

			Spacer(minLength: 4)

			if hasRunTab {
				Button(action: onStop) {
					Label("Stop", systemImage: "stop.fill")
				}
				.buttonStyle(.scaledBordered)
				.help("Stop the build or the running app (Ctrl-C in its tab)")
			}

			Button {
				store.send(.runButtonTapped)
			} label: {
				Label("Run", systemImage: "play.fill")
			}
			.buttonStyle(.scaledBorderedProminent)
			.disabled(!store.canRun)
			.help(runHelp)
		}
		.labelStyle(.titleAndIcon)
		.padding(.horizontal, 10)
		.frame(height: Self.runBarHeight)
	}

	private var schemeMenu: some View {
		Menu {
			ForEach(store.schemes) { scheme in
				Button {
					store.send(.schemeSelected(scheme.name))
				} label: {
					if scheme.name == store.selectedSchemeName {
						Label(scheme.name, systemImage: "checkmark")
					}
					else {
						Text(scheme.name)
					}
				}
			}
		} label: {
			Label(store.selectedSchemeName ?? "Scheme", systemImage: "app.dashed")
				.scaledFont(.subheadline)
				.lineLimit(1)
		}
		.menuStyle(.borderlessButton)
		.fixedSize()
		.disabled(store.schemes.isEmpty)
		.help("The scheme Run builds")
	}

	private var runHelp: String {
		guard let scheme = store.selectedScheme, let device = store.selectedDevice else {
			return "Build and run the app on this simulator"
		}
		return "Build \(scheme.name) and run it on \(device.name) in a terminal tab"
	}

	// MARK: - Header

	private var header: some View {
		HStack(spacing: 6) {
			deviceMenu

			Spacer(minLength: 4)

			if let device = store.selectedDevice {
				if store.transitioningDeviceId == device.id || device.state == .booting {
					ProgressView()
						.controlSize(.small)
				}
				else if device.isBooted {
					if store.isSavingScreenshot {
						ProgressView()
							.controlSize(.small)
							.frame(width: 22, height: 22)
					}
					else {
						iconButton("camera", help: "Save Screenshot") { store.send(.screenshotButtonTapped) }
					}
					recordButton
					iconButton("rotate.left", help: "Rotate Left") { store.send(.rotateButtonTapped(clockwise: false)) }
					iconButton("rotate.right", help: "Rotate Right") { store.send(.rotateButtonTapped(clockwise: true)) }
					if let fold = device.fold {
						if fold.showsInnerPanel {
							iconButton("book.closed", help: "Fold") { store.send(.foldButtonTapped) }
						}
						else {
							iconButton("book", help: "Unfold") { store.send(.foldButtonTapped) }
						}
					}
					iconButton("house", help: "Home") { store.send(.hardwareButtonTapped(.home)) }
					moreMenu
					iconButton("power", help: "Shut down \(device.name)") { store.send(.shutdownButtonTapped) }
				}
				else if store.isRecordingSelectedDevice {
					// simctl may still be finishing a recording of a device that shut down.
					recordButton
				}
			}

			iconButton("xmark", help: "Hide Simulator") {
				store.send(.closeButtonTapped(repositoryPath: repositoryPath))
			}
		}
		.padding(.horizontal, 10)
		.frame(height: Self.headerHeight)
	}

	private var deviceMenu: some View {
		Menu {
			ForEach(store.devices) { device in
				Button {
					store.send(.deviceSelected(device.id))
				} label: {
					if device.id == store.selectedDeviceId {
						Label(menuTitle(for: device), systemImage: "checkmark")
					}
					else {
						Text(menuTitle(for: device))
					}
				}
			}
		} label: {
			Text(store.selectedDevice?.name ?? "No Simulator")
				.scaledFont(.subheadline, weight: .semibold)
				.lineLimit(1)
		}
		.menuStyle(.borderlessButton)
		.fixedSize()
		.labelStyle(.titleAndIcon)
		.disabled(store.devices.isEmpty)
	}

	@ViewBuilder
	private var recordButton: some View {
		if store.isTogglingRecording {
			ProgressView()
				.controlSize(.small)
				.frame(width: 22, height: 22)
		}
		else if store.isRecordingSelectedDevice {
			Button {
				store.send(.recordButtonTapped)
			} label: {
				Image(systemName: "stop.circle.fill")
					.scaledFont(size: 12)
					.foregroundStyle(.red)
					.symbolEffect(.pulse)
					.frame(width: 22, height: 22)
					.contentShape(Rectangle())
			}
			.buttonStyle(.borderless)
			.help("Stop Recording")
		}
		else {
			iconButton("record.circle", help: "Record Screen") { store.send(.recordButtonTapped) }
		}
	}

	/// Simulator.app's Features and the buttons that have no icon of their own here.
	private var moreMenu: some View {
		Menu {
			Button {
				store.send(.memoryWarningButtonTapped)
			} label: {
				Label("Simulate Memory Warning", systemImage: "memorychip")
			}

			Menu {
				Button("None") { store.send(.locationSelected(.clear)) }
				ForEach(SimulatorLocationCommand.places, id: \.name) { place in
					Button(place.name) { store.send(.locationSelected(.set(place.coordinate))) }
				}
				Divider()
				ForEach(SimulatorLocationCommand.knownScenarios, id: \.self) { name in
					Button(name) { store.send(.locationSelected(.scenario(name))) }
				}
			} label: {
				Label("Location", systemImage: "location")
			}

			if let current = store.selectedDevice?.fold {
				Menu {
					ForEach(SimulatorFold.allCases, id: \.self) { fold in
						Button {
							store.send(.foldSelected(fold))
						} label: {
							if fold == current {
								Label(fold.title, systemImage: "checkmark")
							}
							else {
								Text(fold.title)
							}
						}
					}
				} label: {
					Label("Hinge", systemImage: "book")
				}
				.labelStyle(.titleAndIcon)
			}

			Divider()

			ForEach([SimulatorHardwareButton.sideButton, .siri, .volumeUp, .volumeDown, .playPause], id: \.self) { button in
				Button {
					store.send(.hardwareButtonTapped(button))
				} label: {
					Label(button.title, systemImage: Self.icon(for: button))
				}
			}
		} label: {
			Image(systemName: "ellipsis.circle")
				.scaledFont(size: 12)
				.frame(width: 22, height: 22)
				.contentShape(Rectangle())
		}
		.menuStyle(.borderlessButton)
		.menuIndicator(.hidden)
		.fixedSize()
		.labelStyle(.titleAndIcon)
		.help("More")
	}

	private static func icon(for button: SimulatorHardwareButton) -> String {
		switch button {
		case .home:
			"house"
		case .lock, .sideButton:
			"lock"
		case .siri:
			"mic"
		case .volumeUp:
			"speaker.plus"
		case .volumeDown:
			"speaker.minus"
		case .playPause:
			"playpause"
		}
	}

	private func menuTitle(for device: SimulatorDevice) -> String {
		let booted = device.isBooted ? " — Booted" : ""
		return "\(device.name) (\(device.runtimeName))\(booted)"
	}

	private func iconButton(_ systemImage: String, help: String, action: @escaping () -> Void) -> some View {
		Button(action: action) {
			Image(systemName: systemImage)
				.scaledFont(size: 12)
				.frame(width: 22, height: 22)
				.contentShape(Rectangle())
		}
		.buttonStyle(.borderless)
		.help(help)
	}

	// MARK: - Banners

	private var connectBanner: some View {
		BannerView(
			icon: "sparkles",
			title: "Let Claude Code use this simulator",
			subtitle: "Adds the \(ClaudeCodeRegistration.serverName) MCP server to Claude Code. Restart Claude in open tabs to pick it up.",
			color: .accentColor,
			actionLabel: "Connect",
			isLoading: store.isConnectingClaudeCode,
			onAction: { store.send(.connectClaudeCodeButtonTapped) }
		)
	}

	private func noticeBanner(_ notice: SimulatorPaneReducer.Notice) -> some View {
		BannerView(
			icon: notice.icon,
			title: notice.title,
			subtitle: notice.subtitle,
			color: .green,
			actionLabel: notice.fileURL == nil ? nil : "Show in Finder",
			onAction: notice.fileURL == nil ? nil : { store.send(.showNoticeFileInFinderTapped) },
			onDismiss: { store.send(.noticeDismissed) }
		)
		.background(.regularMaterial)
		.clipShape(RoundedRectangle(cornerRadius: 10))
		.shadow(color: .black.opacity(0.2), radius: 8, y: 2)
		.padding(8)
	}

	private func errorBanner(_ message: String) -> some View {
		BannerView(
			icon: "exclamationmark.triangle.fill",
			title: message,
			color: .orange,
			onDismiss: store.errorMessage == nil ? nil : { store.send(.errorDismissed) }
		)
	}

	// MARK: - Screen

	@ViewBuilder
	private var content: some View {
		if let device = store.selectedDevice {
			if device.isBooted {
				SimulatorScreen(deviceId: device.id, screenPixelSize: device.screenPixelSize, screenID: device.screenID)
					.aspectRatio(device.displayedPixelSize, contentMode: .fit)
					.padding(Self.screenPadding)
					.frame(maxWidth: .infinity, maxHeight: .infinity)
			}
			else {
				placeholder {
					Image(systemName: "iphone")
						.scaledFont(size: 40)
						.foregroundStyle(.tertiary)
					Text(device.state == .booting ? "Booting \(device.name)…" : "\(device.name) is \(device.state.label.lowercased())")
						.scaledFont(.callout)
						.foregroundStyle(.secondary)
						.multilineTextAlignment(.center)
					if device.state == .shutdown {
						Button("Boot") { store.send(.bootButtonTapped) }
							.buttonStyle(.scaledBorderedProminent)
							.disabled(store.transitioningDeviceId != nil)
					}
				}
			}
		}
		else {
			placeholder {
				if store.hasLoadedDevices {
					Text("No iOS simulators found. Install an iOS runtime in Xcode ▸ Settings ▸ Components.")
						.scaledFont(.callout)
						.foregroundStyle(.secondary)
						.multilineTextAlignment(.center)
				}
				else {
					ProgressView()
				}
			}
		}
	}

	private func placeholder(@ViewBuilder _ content: () -> some View) -> some View {
		VStack(spacing: 12) {
			content()
		}
		.padding()
		.frame(maxWidth: .infinity, maxHeight: .infinity)
	}
}
