import AppUI
import ComposableArchitecture
import SwiftUI

/// The simulator beside the terminal: a device menu, its controls, and its live screen.
public struct SimulatorPaneView: View {
	let store: StoreOf<SimulatorPaneReducer>
	/// The space the panel offers, from which the pane takes a width that fits the device's
	/// screen at the available height.
	let availableSize: CGSize
	/// The repository whose terminal the pane is beside, which its close button hides it for.
	let repositoryPath: String
	/// The workspace or project the Run button builds; `nil` when the repository has none.
	let projectPath: String?
	/// Whether the repository has a tab that Run opened, which Stop interrupts.
	let hasRunTab: Bool
	/// Interrupts what runs in the run tab (Ctrl-C). The terminal's panes are not in any store,
	/// so the panel does this, not the reducer.
	let onStop: () -> Void

	public init(
		store: StoreOf<SimulatorPaneReducer>,
		availableSize: CGSize,
		repositoryPath: String,
		projectPath: String?,
		hasRunTab: Bool,
		onStop: @escaping () -> Void
	) {
		self.store = store
		self.availableSize = availableSize
		self.repositoryPath = repositoryPath
		self.projectPath = projectPath
		self.hasRunTab = hasRunTab
		self.onStop = onStop
	}

	private static let headerHeight: CGFloat = 36
	private static let runBarHeight: CGFloat = 40
	private static let screenPadding: CGFloat = 12
	private static let minimumWidth: CGFloat = 260
	/// What dragging the pane wider leaves the terminal beside it.
	private static let minimumTerminalWidth: CGFloat = 320
	/// Wider than the 1 pt divider it sits on, so the edge is easy to grab.
	private static let resizeHandleWidth: CGFloat = 8

	/// Set by dragging the pane's leading edge; 0 until then, and after a double-click on the edge,
	/// which leave the width to `fittingWidth`. Clamped where it is read, since it comes back from
	/// user defaults and the window may have shrunk since.
	@AppStorage("simulatorPane.width") private var storedWidth: Double = 0
	/// The width when the current drag began: the drag's translation is measured from its start,
	/// so it applies to that width rather than accumulating onto every intermediate one.
	@State private var dragStartWidth: CGFloat?

	/// The width the user chose, else the fitting one, within limits that keep the terminal usable.
	/// Rotating never changes it — the screen fits itself inside instead.
	private var paneWidth: CGFloat {
		clampedWidth(storedWidth > 0 ? storedWidth : fittingWidth)
	}

	/// Wide enough for the device's screen held portrait at the height left under the header, and
	/// at most half the panel. Portrait rather than the interface's orientation, so it stays put
	/// when the device turns.
	private var fittingWidth: CGFloat {
		let portraitSize = store.selectedDevice.map { $0.portraitRotation.displayedSize(native: $0.screenPixelSize) }
		let aspect: CGFloat = if let portraitSize, portraitSize.height > 0 {
			portraitSize.width / portraitSize.height
		}
		else {
			0.46
		}
		let screenHeight = max(availableSize.height - Self.headerHeight - Self.runBarHeight - Self.screenPadding * 2, 100)
		return min(screenHeight * aspect + Self.screenPadding * 2, availableSize.width * 0.5)
	}

	private func clampedWidth(_ width: CGFloat) -> CGFloat {
		min(max(width, Self.minimumWidth), max(availableSize.width - Self.minimumTerminalWidth, Self.minimumWidth))
	}

	public var body: some View {
		VStack(spacing: 0) {
			header
			Divider()
			if !store.isClaudeCodeConnected {
				connectBanner
				Divider()
			}
			if let message = store.errorMessage ?? store.loadErrorMessage {
				errorBanner(message)
				Divider()
			}
			content
				// Over the screen rather than above it, so saving does not shrink the device.
				.overlay(alignment: .top) {
					if let notice = store.notice {
						noticeBanner(notice)
							.transition(.move(edge: .top).combined(with: .opacity))
					}
				}
				.animation(.easeOut(duration: 0.2), value: store.notice)
			Divider()
			runBar
		}
		.frame(width: paneWidth)
		.background(Color(NSColor.underPageBackgroundColor))
		// Centred on the divider the panel puts before the pane. The pane is drawn after the
		// terminal, so the half reaching past its edge is not covered.
		.overlay(alignment: .leading) {
			resizeHandle
				.offset(x: -Self.resizeHandleWidth / 2)
		}
		// Restarted with the repository, so switching between two repositories that both show the
		// pane switches to the other's device.
		.task(id: repositoryPath) {
			await store.send(.task(repositoryPath: repositoryPath)).finish()
		}
		// Also when the project appears — generated by Tuist while the pane is open.
		.task(id: projectPath) {
			store.send(.projectChanged(projectPath))
		}
	}

	// MARK: - Resizing

	private var resizeHandle: some View {
		Color.clear
			.frame(width: Self.resizeHandleWidth)
			.contentShape(Rectangle())
			.pointerStyle(.frameResize(position: .leading))
			.help("Drag to resize; double-click to fit the device")
			.onTapGesture(count: 2) {
				storedWidth = 0
			}
			.gesture(
				// Global space: the handle moves with the width, so a translation measured in its
				// own space would shift under the pointer as it is dragged.
				DragGesture(minimumDistance: 1, coordinateSpace: .global)
					.onChanged { value in
						let start = dragStartWidth ?? paneWidth
						dragStartWidth = start
						// The handle is on the leading edge: dragging left widens the pane.
						storedWidth = clampedWidth(start - value.translation.width)
					}
					.onEnded { _ in
						dragStartWidth = nil
					}
			)
	}

	// MARK: - Run

	/// Below the screen: which scheme to build, and Run / Stop for the device shown above. When the
	/// pane is too narrow, Run and Stop lose their titles first, then the scheme's name truncates
	/// (last, because a menu that may shrink also stretches, moving its chevron away from the name).
	private var runBar: some View {
		ViewThatFits(in: .horizontal) {
			runBarRow(iconOnly: false, truncatesScheme: false)
			runBarRow(iconOnly: true, truncatesScheme: false)
			runBarRow(iconOnly: true, truncatesScheme: true)
		}
		.padding(.horizontal, 10)
		.frame(height: Self.runBarHeight)
	}

	private func runBarRow(iconOnly: Bool, truncatesScheme: Bool) -> some View {
		HStack(spacing: 8) {
			if projectPath == nil {
				Text("No Xcode project to run")
					.scaledFont(.caption)
					.foregroundStyle(.secondary)
					.lineLimit(1)
			}
			else if store.hasLoadedSchemes, store.schemes.isEmpty {
				Text("No scheme here launches an app")
					.scaledFont(.caption)
					.foregroundStyle(.secondary)
					.lineLimit(1)
					.help("Only shared schemes and your own, saved as .xcscheme files, are listed.")
			}
			else {
				schemeMenu(truncates: truncatesScheme)
			}

			Spacer(minLength: 4)

			if hasRunTab {
				Button(action: onStop) {
					runBarLabel("Stop", systemImage: "stop.fill", iconOnly: iconOnly)
				}
				.buttonStyle(.scaledBordered)
				.help("Stop the build or the running app (Ctrl-C in its tab)")
			}

			Button {
				store.send(.runButtonTapped)
			} label: {
				runBarLabel("Run", systemImage: "play.fill", iconOnly: iconOnly)
			}
			.buttonStyle(.scaledBorderedProminent)
			.disabled(!store.canRun)
			.help(runHelp)
		}
	}

	@ViewBuilder
	private func runBarLabel(_ title: String, systemImage: String, iconOnly: Bool) -> some View {
		if iconOnly {
			Label(title, systemImage: systemImage)
				.labelStyle(.iconOnly)
		}
		else {
			Label(title, systemImage: systemImage)
				.labelStyle(.titleAndIcon)
		}
	}

	private func schemeMenu(truncates: Bool) -> some View {
		Menu {
			ForEach(store.schemes) { scheme in
				Button {
					store.send(.schemeSelected(scheme.name))
				} label: {
					if scheme.name == store.selectedSchemeName {
						Label(scheme.name, systemImage: "checkmark")
					}
					else {
						Text(scheme.name)
					}
				}
			}
		} label: {
			Label(store.selectedSchemeName ?? "Scheme", systemImage: "app.dashed")
				.labelStyle(.titleAndIcon)
				.scaledFont(.subheadline)
				.lineLimit(1)
		}
		.menuStyle(.borderlessButton)
		.fixedSize(horizontal: !truncates, vertical: true)
		.disabled(store.schemes.isEmpty)
		.help("The scheme Run builds")
	}

	private var runHelp: String {
		guard let scheme = store.selectedScheme, let device = store.selectedDevice else {
			return "Build and run the app on this simulator"
		}
		return "Build \(scheme.name) and run it on \(device.name) in a terminal tab"
	}

	// MARK: - Header

	/// How many of the header's controls show as icons; the rest move into the More menu, so the
	/// header fits whatever width the pane gets.
	private enum HeaderDensity {
		/// Every control as an icon.
		case full
		/// Screenshot and rotation in the More menu.
		case compact
		/// Everything but a running recording's stop button in the More menu.
		case minimal
	}

	private var header: some View {
		ViewThatFits(in: .horizontal) {
			headerRow(.full)
			headerRow(.compact)
			headerRow(.minimal)
			// Only when nothing else fits: a menu that may shrink also stretches, which would leave
			// its chevron away from the name.
			headerRow(.minimal, truncatesName: true)
		}
		.padding(.horizontal, 10)
		.frame(height: Self.headerHeight)
	}

	private func headerRow(_ density: HeaderDensity, truncatesName: Bool = false) -> some View {
		HStack(spacing: 6) {
			deviceMenu(truncates: truncatesName)

			Spacer(minLength: 4)

			if let device = store.selectedDevice {
				if store.transitioningDeviceId == device.id || device.state == .booting {
					ProgressView()
						.controlSize(.small)
				}
				else if device.isBooted {
					if store.isSavingScreenshot {
						ProgressView()
							.controlSize(.small)
							.frame(width: 22, height: 22)
					}
					else if density == .full {
						iconButton("camera", help: "Save Screenshot") { store.send(.screenshotButtonTapped) }
					}
					if density != .minimal || store.isRecordingSelectedDevice || store.isTogglingRecording {
						recordButton
					}
					if density == .full {
						iconButton("rotate.left", help: "Rotate Left") { store.send(.rotateButtonTapped(clockwise: false)) }
						iconButton("rotate.right", help: "Rotate Right") { store.send(.rotateButtonTapped(clockwise: true)) }
					}
					// At minimal density the More menu's Hinge submenu folds and unfolds.
					if density != .minimal, let fold = device.fold {
						if fold.showsInnerPanel {
							iconButton("book.closed", help: "Fold") { store.send(.foldButtonTapped) }
						}
						else {
							iconButton("book", help: "Unfold") { store.send(.foldButtonTapped) }
						}
					}
					if density != .minimal {
						iconButton("house", help: "Home") { store.send(.hardwareButtonTapped(.home)) }
					}
					moreMenu(device: device, density: density)
					if density != .minimal {
						iconButton("power", help: "Shut down \(device.name)") { store.send(.shutdownButtonTapped) }
					}
				}
				else if store.isRecordingSelectedDevice {
					// simctl may still be finishing a recording of a device that shut down.
					recordButton
				}
			}

			iconButton("xmark", help: "Hide Simulator") {
				store.send(.closeButtonTapped(repositoryPath: repositoryPath))
			}
		}
	}

	private func deviceMenu(truncates: Bool) -> some View {
		Menu {
			ForEach(store.devices) { device in
				Button {
					store.send(.deviceSelected(device.id))
				} label: {
					if device.id == store.selectedDeviceId {
						Label(menuTitle(for: device), systemImage: "checkmark")
					}
					else {
						Text(menuTitle(for: device))
					}
				}
			}
		} label: {
			Text(store.selectedDevice?.name ?? "No Simulator")
				.scaledFont(.subheadline, weight: .semibold)
				.lineLimit(1)
		}
		.menuStyle(.borderlessButton)
		.fixedSize(horizontal: !truncates, vertical: true)
		.labelStyle(.titleAndIcon)
		.disabled(store.devices.isEmpty)
	}

	@ViewBuilder
	private var recordButton: some View {
		if store.isTogglingRecording {
			ProgressView()
				.controlSize(.small)
				.frame(width: 22, height: 22)
		}
		else if store.isRecordingSelectedDevice {
			Button {
				store.send(.recordButtonTapped)
			} label: {
				Image(systemName: "stop.circle.fill")
					.scaledFont(size: 12)
					.foregroundStyle(.red)
					.symbolEffect(.pulse)
					.frame(width: 22, height: 22)
					.contentShape(Rectangle())
			}
			.buttonStyle(.borderless)
			.help("Stop Recording")
		}
		else {
			iconButton("record.circle", help: "Record Screen") { store.send(.recordButtonTapped) }
		}
	}

	/// Simulator.app's Features, the buttons that have no icon of their own here, and the header's
	/// controls that do not fit at the pane's width.
	private func moreMenu(device: SimulatorDevice, density: HeaderDensity) -> some View {
		Menu {
			if density != .full {
				Button {
					store.send(.screenshotButtonTapped)
				} label: {
					Label("Save Screenshot", systemImage: "camera")
				}
				.disabled(store.isSavingScreenshot)
				if density == .minimal, !store.isRecordingSelectedDevice, !store.isTogglingRecording {
					Button {
						store.send(.recordButtonTapped)
					} label: {
						Label("Record Screen", systemImage: "record.circle")
					}
				}
				Button {
					store.send(.rotateButtonTapped(clockwise: false))
				} label: {
					Label("Rotate Left", systemImage: "rotate.left")
				}
				Button {
					store.send(.rotateButtonTapped(clockwise: true))
				} label: {
					Label("Rotate Right", systemImage: "rotate.right")
				}

				Divider()
			}

			Button {
				store.send(.memoryWarningButtonTapped)
			} label: {
				Label("Simulate Memory Warning", systemImage: "memorychip")
			}

			Menu {
				Button("None") { store.send(.locationSelected(.clear)) }
				ForEach(SimulatorLocationCommand.places, id: \.name) { place in
					Button(place.name) { store.send(.locationSelected(.set(place.coordinate))) }
				}
				Divider()
				ForEach(SimulatorLocationCommand.knownScenarios, id: \.self) { name in
					Button(name) { store.send(.locationSelected(.scenario(name))) }
				}
			} label: {
				Label("Location", systemImage: "location")
			}

			if let current = device.fold {
				Menu {
					ForEach(SimulatorFold.allCases, id: \.self) { fold in
						Button {
							store.send(.foldSelected(fold))
						} label: {
							if fold == current {
								Label(fold.title, systemImage: "checkmark")
							}
							else {
								Text(fold.title)
							}
						}
					}
				} label: {
					Label("Hinge", systemImage: "book")
				}
				.labelStyle(.titleAndIcon)
			}

			Divider()

			ForEach(Self.moreMenuButtons(density: density), id: \.self) { button in
				Button {
					store.send(.hardwareButtonTapped(button))
				} label: {
					Label(button.title, systemImage: Self.icon(for: button))
				}
			}

			if density == .minimal {
				Divider()

				Button {
					store.send(.shutdownButtonTapped)
				} label: {
					Label("Shut Down \(device.name)", systemImage: "power")
				}
			}
		} label: {
			Image(systemName: "ellipsis.circle")
				.scaledFont(size: 12)
				.frame(width: 22, height: 22)
				.contentShape(Rectangle())
		}
		.menuStyle(.borderlessButton)
		.menuIndicator(.hidden)
		.fixedSize()
		.labelStyle(.titleAndIcon)
		.help("More")
	}

	private static func moreMenuButtons(density: HeaderDensity) -> [SimulatorHardwareButton] {
		let buttons: [SimulatorHardwareButton] = [.sideButton, .siri, .volumeUp, .volumeDown, .playPause]
		return density == .minimal ? [.home] + buttons : buttons
	}

	private static func icon(for button: SimulatorHardwareButton) -> String {
		switch button {
		case .home:
			"house"
		case .lock, .sideButton:
			"lock"
		case .siri:
			"mic"
		case .volumeUp:
			"speaker.plus"
		case .volumeDown:
			"speaker.minus"
		case .playPause:
			"playpause"
		}
	}

	private func menuTitle(for device: SimulatorDevice) -> String {
		let booted = device.isBooted ? " — Booted" : ""
		return "\(device.name) (\(device.runtimeName))\(booted)"
	}

	private func iconButton(_ systemImage: String, help: String, action: @escaping () -> Void) -> some View {
		Button(action: action) {
			Image(systemName: systemImage)
				.scaledFont(size: 12)
				.frame(width: 22, height: 22)
				.contentShape(Rectangle())
		}
		.buttonStyle(.borderless)
		.help(help)
	}

	// MARK: - Banners

	private var connectBanner: some View {
		BannerView(
			icon: "sparkles",
			title: "Let Claude Code use this simulator",
			subtitle: "Adds the \(ClaudeCodeRegistration.serverName) MCP server to Claude Code. Restart Claude in open tabs to pick it up.",
			color: .accentColor,
			actionLabel: "Connect",
			isLoading: store.isConnectingClaudeCode,
			onAction: { store.send(.connectClaudeCodeButtonTapped) }
		)
	}

	private func noticeBanner(_ notice: SimulatorPaneReducer.Notice) -> some View {
		BannerView(
			icon: notice.icon,
			title: notice.title,
			subtitle: notice.subtitle,
			color: .green,
			actionLabel: notice.fileURL == nil ? nil : "Show in Finder",
			onAction: notice.fileURL == nil ? nil : { store.send(.showNoticeFileInFinderTapped) },
			onDismiss: { store.send(.noticeDismissed) }
		)
		.background(.regularMaterial)
		.clipShape(RoundedRectangle(cornerRadius: 10))
		.shadow(color: .black.opacity(0.2), radius: 8, y: 2)
		.padding(8)
	}

	private func errorBanner(_ message: String) -> some View {
		BannerView(
			icon: "exclamationmark.triangle.fill",
			title: message,
			color: .orange,
			onDismiss: store.errorMessage == nil ? nil : { store.send(.errorDismissed) }
		)
	}

	// MARK: - Screen

	@ViewBuilder
	private var content: some View {
		if let device = store.selectedDevice {
			if device.isBooted {
				SimulatorScreen(deviceId: device.id, screenPixelSize: device.screenPixelSize, screenID: device.screenID)
					.aspectRatio(device.displayedPixelSize, contentMode: .fit)
					.padding(Self.screenPadding)
					.frame(maxWidth: .infinity, maxHeight: .infinity)
			}
			else {
				placeholder {
					Image(systemName: "iphone")
						.scaledFont(size: 40)
						.foregroundStyle(.tertiary)
					Text(device.state == .booting ? "Booting \(device.name)…" : "\(device.name) is \(device.state.label.lowercased())")
						.scaledFont(.callout)
						.foregroundStyle(.secondary)
						.multilineTextAlignment(.center)
					if device.state == .shutdown {
						Button("Boot") { store.send(.bootButtonTapped) }
							.buttonStyle(.scaledBorderedProminent)
							.disabled(store.transitioningDeviceId != nil)
					}
				}
			}
		}
		else {
			placeholder {
				if store.hasLoadedDevices {
					Text("No iOS simulators found. Install an iOS runtime in Xcode ▸ Settings ▸ Components.")
						.scaledFont(.callout)
						.foregroundStyle(.secondary)
						.multilineTextAlignment(.center)
				}
				else {
					ProgressView()
				}
			}
		}
	}

	private func placeholder(@ViewBuilder _ content: () -> some View) -> some View {
		VStack(spacing: 12) {
			content()
		}
		.padding()
		.frame(maxWidth: .infinity, maxHeight: .infinity)
	}
}
